spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.vzpgcorcskfdlnmzjida
spring.datasource.password=CustomerRelationshipManagement
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.preferQueryMode=simple
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

crm.ai.prompt-version=v1.0
crm.ai.gemini.model=gemini-2.5-flash
crm.ai.gemini.base-url=https://generativelanguage.googleapis.com
crm.ai.gemini.api-key=AIzaSyDqIv2ZCYxLl1bp9Fl2IL9OTY4vXX918pA
crm.ai.max-output-tokens=700
crm.ai.use-mock-when-no-key=false
crm.ai.fallback-when-quota-exceeded=true
crm.ai.fallback-when-invalid-json=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.url=jdbc:postgresql://db.vzpgcorcskfdlnmzjida.supabase.co:5432/postgres?sslmode=require
spring.flyway.user=postgres
spring.flyway.password=CustomerRelationshipManagement